### ISSUE TITLE
Server crashing after placing void ore miner

### ISSUE THREAD

**Issue by MasterP2010** [ValkyrieofNight/EnvironmentalTech#18]
Hello, since our server crashes every time we place some blocks of the void ore miner tier 1 multiblock, I decided to report this issue to you. I really enjoy your mod by the way! :P

EDIT: The server is not really crashing as you can see from the log. You just get kicked and can't rejoin. When you try to rejoin you get the same massage as if you would have been kicked. So no specific error there. Also my singleplayer map crashed after placing and assembling the ore miner.

A list of all installed mods can be found here: http://www2.pic-upload.de/img/32418759/Unbenannt.png

[18:10:57] [Server thread/ERROR] [FML]: A TileEntity type com.valkyrieofnight.valkyrielib.multiblock.VLTileSlave has throw an exception trying to write state. It will not persist. Report this to the mod author java.lang.RuntimeException: class com.valkyrieofnight.valkyrielib.multiblock.VLTileSlave is missing a mapping! This is a bug!         at net.minecraft.tileentity.TileEntity.func_189516_d(TileEntity.java:78) ~[asc.class:?]         at net.minecraft.tileentity.TileEntity.func_189515_b(TileEntity.java:69) ~[asc.class:?]         at com.valkyrieofnight.valkyrielib.multiblock.VLTileSlave.func_189515_b(VLTileSlave.java:83) ~[VLTileSlave.class:?]         at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:393) [avd.class:?]         at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:184) [avd.class:?]         at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:203) [lv.class:?]         at net.minecraft.world.gen.ChunkProviderServer.func_186027_a(ChunkProviderServer.java:231) [lv.class:?]         at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1015) [lw.class:?]         at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:366) [MinecraftServer.class:?]         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:647) [MinecraftServer.class:?]         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]         at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]

**Comment by ValkyrieofNight** [comment]
Thanks for the report. Will take a look into this later today.

**Comment by ValkyrieofNight** [comment]
Thanks for the info. Working on this today. Might have a new build out tonight.

**Comment by ValkyrieofNight** [comment]
I believe I have fixed the problem. Will be pushing an update soon.
