### ISSUE TITLE
Crash on server launch

### ISSUE THREAD

**Issue by Letoric** [ValkyrieofNight/EnvironmentalTech#236]
Crash Report UUID: a4c3baef-b7fc-48ca-a32f-4680a7447c04[09:09:39] [main/FATAL] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Environmental Tech (envirotech) has failed to load correctly
?7java.lang.BootstrapMethodError: java.lang.IllegalAccessError: no such constructor: com.valkyrieofnight.envirotech.m_voidminer.ui.VoidMinerContainer.<init>(int,PlayerInventory,PacketBuffer)void/newInvokeSpecial
]
        at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:263) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:230) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:188) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44) ~[forge:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading}
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261] {}
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261] {}
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261] {}
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261] {}
        at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.4-35.1.28.jar:35.1] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {re:classloading}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {re:classloading}
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.4-35.1.28.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.4-35.1.28.jar:?] {}
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.4-35.1.28.jar:?] {}

Seems like this may not have been tested on multiplayer? I started with forge 35.1.13, upgraded to see if it could resolve it, but no luck.

**Comment by ValkyrieofNight** [comment]
Looks like your might need to update one of my mods.

**Comment by Letoric** [comment]
That was with your updates from yesterday on valkyrie, env mats, and env
tech

**Comment by ValkyrieofNight** [comment]
Can you list all the versions you are running?

**Comment by Letoric** [comment]
I deleted them and reverted to the prior versions:
enviromats-1.16.4-2.0.5.0
 envirotech-1.16.4-3.0.5.1
valkyrielib-1.16.4-3.0.5.2

I update ~2-3 times per day, I know without a doubt I was on the 3 files
that were released ~2 days ago, when I submitted the issue.
Valkyrie Lib, Enviro Mats, and Enviro Tech were the 3 that were updated at
that time.Sorry I can't offer exact versions, server boots crashes don't
give crash logs a lot of the time that echo all the versions.


Here is the approximate time/date of when it started, in CST, which
correlates to when I downloaded the files from Curse.
[01Jan2021 09:09:39.298]
[01Jan2021 09:02:47.654]

Hope this helps.

**Comment by ValkyrieofNight** [comment]
Those are out of date. The latest versions are X.X.6.X

**Comment by Letoric** [comment]
I know those are out of date, that's what I rolled back to man lol. Did you
miss the rest of my message? Since I had rolled back, I couldn't
explicitly tell you which version I had updated to, other than referring to
Curse, all I can say is I pulled down the 3 files that were current on that
day.

Anyway, if you can't reproduce it, close it. If you're not trying to, that
would be disappointing :P

Thanks for the mod.

**Comment by Letoric** [comment]
I found the issue. I'm not sure why (other than curseforge is kinda in a
bad place right now) but I didn't see the updates for enviro energy or
enviro core, so those were not updated. Now that all 5 mods are updated, it
boots ok.
