### ISSUE TITLE
BUG: Crash when void miner built inside custom dimension

### ISSUE THREAD

**Issue by Skriglitz** [ValkyrieofNight/EnvironmentalTech#247]
We came across an issue on our server where if a void miner is completed inside a dimension with a custom ResourceLocation such as JAMD/JAVD, would result in a NPE and crash the client if SP, and server if MP.

ValkyrieLib Version: 3.0.5.2
Environmental Tech Version:  3.0.5.1
Modpack Name: FTB Direwolf20 1.16 v1.2.0
How to reproduce bug: Enter either JAMD or JAVD dimension and build any Void Miner. Upon completion will instantly crash with NPE. 

Crash report stack trace:
```
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 1/8/21 12:49 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
        at com.valkyrieofnight.vlib.core.util.wrapped.VLID.from(VLID.java:56) ~[valkyrielib:1.16.4-3.0.5.2] {re:classloading}
        at com.valkyrieofnight.vlib.core.util.wrapped.VLID.from(VLID.java:87) ~[valkyrielib:1.16.4-3.0.5.2] {re:classloading}
        at com.valkyrieofnight.envirotech.m_voidminer.tile.VoidMinerCCUTile.onMultiblockFormed(VoidMinerCCUTile.java:426) ~[envirotech:1.16.4-3.0.5.1123] {re:classloading,pl:runtimedistcleaner:A}
        at com.valkyrieofnight.vlib.multiblock.obj.tile.impl.ControllerTile.internalOnMultiblockFormed(ControllerTile.java:124) ~[valkyrielib:1.16.4-3.0.5.2] {re:classloading}
        at com.valkyrieofnight.vlib.multiblock.constructor.ContinuousConstructor.changeState(ContinuousConstructor.java:241) ~[valkyrielib:1.16.4-3.0.5.2] {re:classloading}
        at com.valkyrieofnight.vlib.multiblock.constructor.ContinuousConstructor.tick(ContinuousConstructor.java:188) ~[valkyrielib:1.16.4-3.0.5.2] {re:classloading}
        at com.valkyrieofnight.vlib.multiblock.obj.tile.impl.ControllerTile.func_73660_a(ControllerTile.java:183) ~[valkyrielib:1.16.4-3.0.5.2] {re:classloading}
        at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
        at com.valkyrieofnight.vlib.core.util.wrapped.VLID.from(VLID.java:56) ~[valkyrielib:1.16.4-3.0.5.2] {re:classloading}
        at com.valkyrieofnight.vlib.core.util.wrapped.VLID.from(VLID.java:87) ~[valkyrielib:1.16.4-3.0.5.2] {re:classloading}
        at com.valkyrieofnight.envirotech.m_voidminer.tile.VoidMinerCCUTile.onMultiblockFormed(VoidMinerCCUTile.java:426) ~[envirotech:1.16.4-3.0.5.1123] {re:classloading,pl:runtimedistcleaner:A}
        at com.valkyrieofnight.vlib.multiblock.obj.tile.impl.ControllerTile.internalOnMultiblockFormed(ControllerTile.java:124) ~[valkyrielib:1.16.4-3.0.5.2] {re:classloading}
        at com.valkyrieofnight.vlib.multiblock.constructor.ContinuousConstructor.changeState(ContinuousConstructor.java:241) ~[valkyrielib:1.16.4-3.0.5.2] {re:classloading}
        at com.valkyrieofnight.vlib.multiblock.constructor.ContinuousConstructor.tick(ContinuousConstructor.java:188) ~[valkyrielib:1.16.4-3.0.5.2] {re:classloading}
        at com.valkyrieofnight.vlib.multiblock.obj.tile.impl.ControllerTile.func_73660_a(ControllerTile.java:183) ~[valkyrielib:1.16.4-3.0.5.2] {re:classloading}
-- Block entity being ticked --
Details:
        Name: envirotech:litherite_void_miner_ccu // com.valkyrieofnight.envirotech.m_voidminer.tile.VMCCU1
        Block: Block{envirotech:litherite_void_miner_ccu}[facing=up]
        Block location: World: (22790,126,28511), Chunk: (at 6,7,15 in 1424,1781; contains blocks 22784,0,28496 to 22799,255,28511), Region: (44,55; contains chunks 1408,1760 to 1439,1791, blocks 22528,0,28160 to 23039,255,28671)
        Block: Block{envirotech:litherite_void_miner_ccu}[facing=up]
        Block location: World: (22790,126,28511), Chunk: (at 6,7,15 in 1424,1781; contains blocks 22784,0,28496 to 22799,255,28511), Region: (44,55; contains chunks 1408,1760 to 1439,1791, blocks 22528,0,28160 to 23039,255,28671)
Stacktrace:r
        at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
```

**Comment by ValkyrieofNight** [comment]
Try updating to the latest versions this should be fixed in those.

**Comment by Skriglitz** [comment]
I didn't see there was a new release.. But I did replace it in the modpack and tested and it is indeed working the dimensions now without issues. Thanks!
