### ISSUE TITLE
Error Occurse if Player Join

### ISSUE THREAD

**Issue by SpecialT131** [ValkyrieofNight/EnvironmentalTech#27]
Forge Server Version: 1.11.2 - 13.20.0.2252

Errorcode:
`[19:08:52] [Server thread/ERROR]: Failed to create block entity environmentaltech:lens_colored.tile
java.lang.InstantiationException: com.valkyrieofnight.environmentaltech.block.multiblock.voidoreminer.BlockLaserLensColored$LLC_SLAVE
	at java.lang.Class.newInstance(Class.java:427) ~[?:1.8.0_121]
	at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:105) [asc.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:490) [avd.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:96) [ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) [ChunkIOExecutor.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:119) [lv.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:90) [lv.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:136) [lv.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:303) [ajs.class:?]
	at net.minecraft.world.World.func_175726_f(World.java:298) [ajs.class:?]
	at net.minecraft.world.World.func_180495_p(World.java:903) [ajs.class:?]
	at net.minecraft.tileentity.TileEntityChest.func_174912_b(TileEntityChest.java:207) [ase.class:?]
	at net.minecraft.tileentity.TileEntityChest.func_174911_a(TileEntityChest.java:184) [ase.class:?]
	at net.minecraft.tileentity.TileEntityChest.func_145979_i(TileEntityChest.java:174) [ase.class:?]
	at net.minecraft.tileentity.TileEntityChest.func_73660_a(TileEntityChest.java:214) [ase.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1801) [ajs.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621) [lw.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NoSuchMethodException: com.valkyrieofnight.environmentaltech.block.multiblock.voidoreminer.BlockLaserLensColored$LLC_SLAVE.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082) ~[?:1.8.0_121]
	at java.lang.Class.newInstance(Class.java:412) ~[?:1.8.0_121]
	... 21 more
[19:08:52] [Server thread/WARN]: Skipping BlockEntity with id environmentaltech:lens_colored.tile
[19:08:52] [Server thread/ERROR]: Failed to create block entity environmentaltech:laser_core.tile
java.lang.InstantiationException: com.valkyrieofnight.environmentaltech.block.multiblock.voidoreminer.BlockLaserCore$LL_SLAVE
	at java.lang.Class.newInstance(Class.java:427) ~[?:1.8.0_121]
	at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:105) [asc.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:490) [avd.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:96) [ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) [ChunkIOExecutor.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:119) [lv.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:90) [lv.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:136) [lv.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:303) [ajs.class:?]
	at net.minecraft.world.World.func_175726_f(World.java:298) [ajs.class:?]
	at net.minecraft.world.World.func_180495_p(World.java:903) [ajs.class:?]
	at net.minecraft.tileentity.TileEntityChest.func_174912_b(TileEntityChest.java:207) [ase.class:?]
	at net.minecraft.tileentity.TileEntityChest.func_174911_a(TileEntityChest.java:184) [ase.class:?]
	at net.minecraft.tileentity.TileEntityChest.func_145979_i(TileEntityChest.java:174) [ase.class:?]
	at net.minecraft.tileentity.TileEntityChest.func_73660_a(TileEntityChest.java:214) [ase.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1801) [ajs.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621) [lw.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NoSuchMethodException: com.valkyrieofnight.environmentaltech.block.multiblock.voidoreminer.BlockLaserCore$LL_SLAVE.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082) ~[?:1.8.0_121]
	at java.lang.Class.newInstance(Class.java:412) ~[?:1.8.0_121]
	... 21 more
[19:08:52] [Server thread/WARN]: Skipping BlockEntity with id environmentaltech:laser_core.tile
[19:08:52] [Server thread/ERROR]: Failed to create block entity environmentaltech:laser_core.tile
java.lang.InstantiationException: com.valkyrieofnight.environmentaltech.block.multiblock.voidoreminer.BlockLaserCore$LL_SLAVE
	at java.lang.Class.newInstance(Class.java:427) ~[?:1.8.0_121]
	at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:105) [asc.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:490) [avd.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:96) [ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) [ChunkIOExecutor.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:119) [lv.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:90) [lv.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:136) [lv.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:303) [ajs.class:?]
	at net.minecraft.world.World.func_175726_f(World.java:298) [ajs.class:?]
	at net.minecraft.world.World.func_180495_p(World.java:903) [ajs.class:?]
	at net.minecraft.tileentity.TileEntityChest.func_174912_b(TileEntityChest.java:207) [ase.class:?]
	at net.minecraft.tileentity.TileEntityChest.func_174911_a(TileEntityChest.java:184) [ase.class:?]
	at net.minecraft.tileentity.TileEntityChest.func_145979_i(TileEntityChest.java:174) [ase.class:?]
	at net.minecraft.tileentity.TileEntityChest.func_73660_a(TileEntityChest.java:214) [ase.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1801) [ajs.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621) [lw.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NoSuchMethodException: com.valkyrieofnight.environmentaltech.block.multiblock.voidoreminer.BlockLaserCore$LL_SLAVE.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082) ~[?:1.8.0_121]
	at java.lang.Class.newInstance(Class.java:412) ~[?:1.8.0_121]
	... 21 more`

**Comment by ValkyrieofNight** [comment]
Sorry 1.11.2 is no longer supported due to MC 1.12 and ET 2. ET 2 may be back-ported at some point however.
