### ISSUE TITLE
oddness noticed in console on server(environmentaltech-1.11.2-0.11.0d)

### ISSUE THREAD

**Issue by SDUBZ** [ValkyrieofNight/EnvironmentalTech#38]
forge:1.11.2-2282
23:09:27] [Server thread/ERROR]: Failed to create block entity environmentaltech:laser_core.tilejava.lang.InstantiationException: com.valkyrieofnight.environmentaltech.block.multiblock.voidoreminer.BlockLaserCore$LL_SLAVEat java.lang.Class.newInstance(Class.java:427) ~[?:1.8.0_112]at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:105) [asc.class:?]at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:490) [avd.class:?]at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:96) [ChunkIOProvider.class:?]at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) [ChunkIOExecutor.class:?]at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:119) [lv.class:?]at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:90) [lv.class:?]at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:136) [lv.class:?]at net.minecraft.world.World.func_72964_e(World.java:303) [ajs.class:?]at net.minecraftforge.common.ForgeChunkManager$1.apply(ForgeChunkManager.java:142) [ForgeChunkManager$1.class:?]at net.minecraftforge.common.ForgeChunkManager$1.apply(ForgeChunkManager.java:137) [ForgeChunkManager$1.class:?]at com.google.common.collect.Iterators$8.transform(Iterators.java:794) [minecraft_server.1.11.2.jar:?]at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48) [minecraft_server.1.11.2.jar:?]at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:301) [minecraft_server.1.11.2.jar:?]at com.google.common.collect.ImmutableSet$Builder.addAll(ImmutableSet.java:522) [minecraft_server.1.11.2.jar:?]at net.minecraftforge.common.ForgeChunkManager.getPersistentChunksIterableFor(ForgeChunkManager.java:137) [ForgeChunkManager.class:?]at net.minecraft.world.World.getPersistentChunkIterable(World.java:3837) [ajs.class:?]at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:388) [lw.class:?]at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:219) [lw.class:?]at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) [MinecraftServer.class:?]at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]Caused by: java.lang.NoSuchMethodException: com.valkyrieofnight.environmentaltech.block.multiblock.voidoreminer.BlockLaserCore$LL_SLAVE.()at java.lang.Class.getConstructor0(Class.java:3082) ~[?:1.8.0_112]at java.lang.Class.newInstance(Class.java:412) ~[?:1.8.0_112]... 23 more

**Comment by LittleODie** [comment]
Having my console constantly spammed with this as well as a few crashes.

**Comment by kreezxil** [comment]
confirmed
`[06:27:07] [Server thread/ERROR]: Failed to create block entity environmentaltech:laser_core.tile
java.lang.InstantiationException: com.valkyrieofnight.environmentaltech.block.multiblock.voidoreminer.BlockLaserCore$LL_SLAVE
        at java.lang.Class.newInstance(Class.java:427) ~[?:1.8.0_121]
        at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:105) [asc.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:490) [avd.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:96) [ChunkIOProvider.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) [ChunkIOExecutor.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:119) [lv.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:90) [lv.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:136) [lv.class:?]
        at net.minecraft.world.World.func_72964_e(World.java:303) [ajs.class:?]
        at net.minecraft.world.World.func_175726_f(World.java:298) [ajs.class:?]
        at net.minecraft.world.World.func_175625_s(World.java:2359) [ajs.class:?]
        at com.raoulvdberge.refinedstorage.apiimpl.network.node.NetworkNode.getFacingTile(NetworkNode.java:166) [NetworkNode.class:?]
        at com.raoulvdberge.refinedstorage.apiimpl.network.node.NetworkNodeImporter.update(NetworkNodeImporter.java:63) [NetworkNodeImporter.class:?]
        at com.raoulvdberge.refinedstorage.apiimpl.network.NetworkNodeListener.onWorldTick(NetworkNodeListener.java:23) [NetworkNodeListener.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_344_NetworkNodeListener_onWorldTick_WorldTickEvent.invoke(.dynamic) [?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:269) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:729) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NoSuchMethodException: com.valkyrieofnight.environmentaltech.block.multiblock.voidoreminer.BlockLaserCore$LL_SLAVE.<init>()
        at java.lang.Class.getConstructor0(Class.java:3082) ~[?:1.8.0_121]
        at java.lang.Class.newInstance(Class.java:412) ~[?:1.8.0_121]
        ... 22 more
`

**Comment by kreezxil** [comment]
My console is also getting spammed

**Comment by Mohron** [comment]
Same spam on our console :(

**Comment by ValkyrieofNight** [comment]
Sorry 1.11.2 is no longer supported due to MC 1.12 and ET 2.

**Comment by ValkyrieofNight** [comment]
ET 2 may be back-ported at some point however.

**Comment by Ricket** [comment]
Does this affect functionality at all? Is something broken, is there something we should avoid doing or watch out for, or some workaround?
